services:
  inventory-service:
    build:
      context: .
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8082:8082"
    env_file:
      - .env